### ISSUE TITLE
Dialog's Inputtext

### ISSUE THREAD

**Issue by tr1xy** [openmultiplayer/samp-bugs#38]
This bug probably won't be persistent in open.mp but I still have to report it.

_OnDialogResponse's **inputtext[]**_ inherits the string of DIALOG_STYLE_LIST's item.

Example:
```
#include <a_samp>

main() {}

public OnPlayerConnect(playerid)
{
	ShowPlayerDialog(playerid, 1, DIALOG_STYLE_LIST, "CAPTION", "1\n2\n3", "X", "O");
	return 1;
}

public OnDialogResponse(playerid, dialogid, response, listitem, inputtext[])
{
	if(dialogid == 1)
	{
		// 1, 2 or 3
		SendClientMessage(playerid, -1, inputtext);
	}
	return 1;
}
```

I'll die.

**Comment by EvilShadeZ** [comment]
I wouldn't call this a bug, but rather an intended feature of the server. There are quite a few occasions where you wanna retrieve the field without having prior knowledge of its contents. This should definitely NOT be patched out as it WILL break systems that rely on this feature.

If you check SA-MP wiki, it is the intended behaviour for it: 
https://wiki.sa-mp.com/wiki/OnDialogResponse

Also, I have a system which relies on this. Rather than creating a ridiculously sized array for a list-based mysql response, I use the data in the inputtext to find which field was actually pressed.

**Comment by Y-Less** [comment]
Yeah, it looked correct to me as well.
